### ISSUE TITLE
google search bar tile

### ISSUE THREAD

**Issue by CorruptionVR** [frabarz/new-metrotab#2]
Is there any way that I can add a google search bar in a tile? one that I can click on and type without changing screens?

**Comment by CorruptionVR** [comment]
![example](https://user-images.githubusercontent.com/78228404/167443176-af8d63f1-3e83-4302-9ee3-7f6b071ac5bc.png)
like this

**Comment by CorruptionVR** [comment]
@frabarz

**Comment by thierry-laval** [comment]
very good idea! Where can we fork the project?

**Comment by frabarz** [comment]
Well, as the repo says, there's no way to make modifications to the current extension, but a fork/revival like @thierry-laval's can be done. As far as I remember predefined tiles use custom code on the setup, so adding an <input/> should be possible.
...though, why not just using the address bar of the browser?

**Comment by thierry-laval** [comment]
I made this fork to study the code and see what I can do. Well, we'll have to be patient because I'll do it on my free time. 

But this extension is really well thought that it's a pleasure to use it. 

Congratulations again to the great developer who created it.

It's true that being able to integrate more things in the tiles, like a search engine can be nice. Yes the engine can be used in the search bar. The usefulness can be found when you use the browser in full screen and just want to go through the interface. Why not include an application launcher... Anything is possible! 

But for now let's keep it simple and the launch of favorites put under tiles is just great.
We will improve it :-) 

Thanks again to the creator. @frabarz
